FROM debian:bullseye

RUN apt update && apt upgrade -y && apt install -y \
        curl \
        git \
        build-essential \
        cmake \
        jq \
        mosquitto-clients \
        less \
        nano \
        setserial \
        pcregrep

ADD sources/inverter-cli/ /opt/inverter-cli/
ADD config/ /etc/inverter/

RUN cd /opt/inverter-cli && \
    mkdir bin && cmake . && make && mv inverter_poller bin/

ADD sources/healthcheck /opt/
ADD sources/inverter-mqtt/ /opt/inverter-mqtt/

HEALTHCHECK \
    --interval=10s \
    --timeout=6s \
    --start-period=40s \
    --retries=3 \
  CMD /opt/healthcheck

WORKDIR /opt
ENTRYPOINT ["/bin/bash", "/opt/inverter-mqtt/entrypoint.sh"]
