version: '3'

# use start.sh and stop.sh to run as it'll set the variables

services:
  mqtt:
    build:
      context: .
      dockerfile: Dockerfile.dev

    container_name: "${CONTAINER_NAME}"

    privileged: false
    restart: always

    volumes:
        - ./config/:/etc/inverter/

    devices:
      - "${DEVICE}:${DEVICE}"

  # Used to auto-update images as we release new versions...
#  watchtower:
    # Please see the following for configuration options:
    #    https://containrrr.github.io/watchtower/container-selection/
#    image: containrrr/watchtower
#    container_name: watchtower

#    restart: always
#    privileged: true

#    volumes:
#      - /var/run/docker.sock:/var/run/docker.sock

#    command: --interval 500

